/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Configuracion_guantes;

import javax.swing.JOptionPane;
import kurokami.monitor.Monitor;

/**
 *
 * @author Gilda
 */
public class Guantes extends javax.swing.JPanel {

    int cantidad = 0;
    Monitor monitor;

    /**
     * Creates new form Guantes
     */
    public Guantes(Monitor monitor) {
        initComponents();
        this.monitor = monitor;
    }

    public void verificacion(int cant) {
        int no_oponentes = this.monitor.getNumeroOponentes();
        int diferencia = 0;
        diferencia = cant - no_oponentes;
//        if (diferencia != 1) {
//            if (diferencia < 0) {
//                JOptionPane.showMessageDialog(null, "No es posible realizar el cambio, "
//                        + " No hay suficientes guantes", "mensaje", JOptionPane.INFORMATION_MESSAGE);
//            } 
//            else {
//                JOptionPane.showMessageDialog(null, "No es posible realizar el cambio, "
//                        + "Deben de haber menos guantes", "mensaje", JOptionPane.INFORMATION_MESSAGE);
//            }
//        }
        if (cant < 5) {
            JOptionPane.showMessageDialog(null, "No es posible realizar el cambio, "
                    + " No hay suficientes guantes", "mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            confirmacion(cant);

        }
    }

    public void confirmacion(int cant) {
        this.monitor.setGuantesDisponibles(cant);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Configuracion de cantidad de guantes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 67, 481, 35));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 162, 375, -1));

        jLabel2.setText("Cantidad de guantes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 174, -1, -1));

        jButton1.setText("Realizar ajuste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 268, 415, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cantidad_Texto = "";
        cantidad_Texto = jTextField1.getText();
        int cantidad1 = Integer.parseInt(cantidad_Texto);
        verificacion(cantidad1);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
