/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consumidor;

import kurokami.monitor.*;

/**
 *
 * @author marcos
 */
public class Consumidor extends javax.swing.JPanel {
    Monitor monitor;
    int contador;
    consumidor_t c;
    /**
     * Creates new form consumidor
     * @param monitor
     * @param c
     */
    public Consumidor(Monitor monitor, consumidor_t c) {
        initComponents();
        this.monitor = monitor;
        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista_boxeadores_at = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tiempoRestante = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        colaBoxeadores = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista_boxeadores_at.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_boxeadores_at.setPreferredSize(new java.awt.Dimension(70, 250));
        jScrollPane1.setViewportView(lista_boxeadores_at);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 64, 150, 250));

        tiempoRestante.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(tiempoRestante);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 64, 150, 250));

        colaBoxeadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(colaBoxeadores);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 64, 150, 250));

        jButton1.setText("Nuevo Boxeador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 332, 236, -1));

        jLabel1.setText("ID Boxeador");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 41, -1, -1));

        jLabel2.setText("Tiempo Boxeador");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 41, -1, -1));

        jLabel3.setText("Cola de Espera");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 41, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Boxeador nuevoBoxeador = new Boxeador(contador, (int)(Math.random()*10), this.monitor, this.c);
        monitor.agregarBoxeador(nuevoBoxeador);
        contador +=1;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> colaBoxeadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JList<String> lista_boxeadores_at;
    public static javax.swing.JList<String> tiempoRestante;
    // End of variables declaration//GEN-END:variables
}
